<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ObjetoGasto;

class ClasificadorObjetoGastoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $catalogos = [
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '11100001', 'descripcion' => 'Dietas'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '11300001', 'descripcion' => 'Sueldos y Salarios'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '11300002', 'descripcion' => 'Sobresueldo Jerarquización Terciaria Policial'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '12100001', 'descripcion' => 'Personal de Lista de Raya'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '12100002', 'descripcion' => 'Honorarios Profesionales'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '12100003', 'descripcion' => 'Honorarios por Ejecución'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '12200001', 'descripcion' => 'Sueldos al Personal Eventual'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '12200002', 'descripcion' => 'Suplencias'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '12200003', 'descripcion' => 'Sueldos al Empleado Temporal Administrativo'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '12300001', 'descripcion' => 'Remuneraciones por Servicios Especiales'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '12300002', 'descripcion' => 'Ayuda por Servicios'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '13100001', 'descripcion' => 'Quinquenios'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '13100002', 'descripcion' => 'Quinquenios Nueva Generación'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '13200001', 'descripcion' => 'Prima Dominical'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '13200002', 'descripcion' => 'Gratificación Anual'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '13200003', 'descripcion' => 'Prima Vacacional'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '13200004', 'descripcion' => 'Bono Anual de Despensa'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '13200005', 'descripcion' => 'Canasta Navideña'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '13300001', 'descripcion' => 'Compensación por Servicios de Turno Vespertino'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '13400001', 'descripcion' => 'Compensaciones Fijas'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '13400002', 'descripcion' => 'Compensación de Escaso Desarrollo'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '13400003', 'descripcion' => 'Participaciones al Personal'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '13400004', 'descripcion' => 'Compensación por Asignación Pedagógica Específica'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '13400005', 'descripcion' => 'Compensación por Ajuste de Calendario'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '13400006', 'descripcion' => 'Compensación Docente'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '13400007', 'descripcion' => 'Compensación Administrativa'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '14100001', 'descripcion' => 'Instituto Mexicano del Seguro Social'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '14100002', 'descripcion' => 'Seguro Institucional'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '14100003', 'descripcion' => 'Issste - Instituto de Seguridad y Servicios Sociales de los Trabajadores del Estado'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '14100004', 'descripcion' => 'Seguro de Vida y Pago de Marcha'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '14200001', 'descripcion' => 'FOVISSSTE - Fondo de Vivienda del ISSSTE'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '14300001', 'descripcion' => 'Sistema de Ahorro para el Retiro'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '14300002', 'descripcion' => 'Seguro de Retiro'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15200001', 'descripcion' => 'Pensiones, Jubilaciones e Indemnizaciones'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15300001', 'descripcion' => 'Liquidaciones por Indemnizaciones y por Sueldos y Salarios Caídos'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400001', 'descripcion' => 'Ayuda para Pasajes'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400002', 'descripcion' => 'Ayuda para Lentes y Aparatos Ortopédicos'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400003', 'descripcion' => 'Material Didáctico'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400004', 'descripcion' => 'Despensa'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400005', 'descripcion' => 'Previsión Social Múltiple'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400006', 'descripcion' => 'Compensación por Actividad Curricular'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400007', 'descripcion' => 'Pago de Días Económicos No Disfrutados'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400008', 'descripcion' => 'Asignación Docente Genérica'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400009', 'descripcion' => 'Asignación Docente Específica'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400110', 'descripcion' => 'Ayuda para Impresión de Tesis'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400111', 'descripcion' => 'Canastilla Maternal'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400112', 'descripcion' => 'Días de Descanso Obligatorio'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400113', 'descripcion' => 'Servicio de Guarderías'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400114', 'descripcion' => 'Ayuda para la Adquisición de Útiles Escolares'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400115', 'descripcion' => 'Cuota Fija para Personal de Asignatura'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400116', 'descripcion' => 'Compensación por Actuación y Productividad'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400117', 'descripcion' => 'Pago del Día de las Madres'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400118', 'descripcion' => 'Ayuda A Supervisores para Gastos de Traslado'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400119', 'descripcion' => 'Gratificación Administrativa'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400220', 'descripcion' => 'Compensación E3 Arraigo al Maestro en el Medio Rural'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400221', 'descripcion' => 'Compensación I-2'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400222', 'descripcion' => 'Compensación Provisional Compactable'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400223', 'descripcion' => 'Compensación Temporal Compactable'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400224', 'descripcion' => 'Regularización a la Función'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400225', 'descripcion' => 'Asignación por Actividades Culturales'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400226', 'descripcion' => 'Previsión Social para Policías'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400227', 'descripcion' => 'Apoyo a la Integración Educativa'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400228', 'descripcion' => 'Atención a Grupos Multigrado'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400229', 'descripcion' => 'Ayuda de Previsión Social por Riesgo de Seguridad Pública'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400330', 'descripcion' => 'Gratificación Extraordinaria'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400331', 'descripcion' => 'Gratificación'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400332', 'descripcion' => 'Compensación por Servicios Especiales'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400333', 'descripcion' => 'Servicios Conmemorativos'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15400034', 'descripcion' => 'Despensa Participable para ISR'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15500001', 'descripcion' => 'Compensación por Incorporación al Programa de Carrera Administrativa'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '15500002', 'descripcion' => 'Ayuda para Capacitación y Desarrollo'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '16100001', 'descripcion' => 'Previsiones de Carácter Laboral, Económica y de Seguridad Social'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '17100001', 'descripcion' => 'Estímulo por Antigüedad'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '17100002', 'descripcion' => 'Estímulo por Licenciatura'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '17100003', 'descripcion' => 'Titulaciones'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '17100004', 'descripcion' => 'Estímulo por Puntualidad y Asistencia'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '17100005', 'descripcion' => 'Estímulo por Antigüedad (Docentes)'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '17100006', 'descripcion' => 'Estímulo a Servidores Públicos'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '17100007', 'descripcion' => 'Premio Mensual por Buen Desempeño'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '17100008', 'descripcion' => 'Estímulo por Productividad'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '17100009', 'descripcion' => 'Servicios Cocurriculares'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '17100110', 'descripcion' => 'Estímulo al Destacado Desempeño'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '17100111', 'descripcion' => 'Estímulo por Promoción en la Función'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '17100112', 'descripcion' => 'Estímulo Fijo de Carrera Magisterial'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '17100113', 'descripcion' => 'Incentivos Asesores Técnico-Pedagógico'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '17100114', 'descripcion' => 'Estímulo Fijo de Carrera Magisterial Asignación Docente Genérica'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '17100115', 'descripcion' => 'Estímulo Fijo de Carrera Magisterial  Compensación Provisional Compactable'],
            ['capitulo' => '1000_(Serv._Personales)', 'partida' => '17100116', 'descripcion' => 'Incentivo a Tutores'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '21100001', 'descripcion' => 'Materiales y Útiles de Oficina'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '21200001', 'descripcion' => 'Materiales y Útiles de Impresión y Reproducción'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '21200002', 'descripcion' => 'Material de Fotografía'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '21400001', 'descripcion' => 'Materiales y Útiles para el Procesamiento en Equipos y Bienes Informáticos'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '21500001', 'descripcion' => 'Material para Información'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '21500002', 'descripcion' => 'Suscripción a Periódicos y Medios Informativos'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '21500003', 'descripcion' => 'Material de Cinematografía y Audiovisual'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '21600001', 'descripcion' => 'Material de Limpieza'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '21700001', 'descripcion' => 'Material Didáctico'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '21800001', 'descripcion' => 'Valores de Tránsito'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '22100001', 'descripcion' => 'Productos Alimenticios para los Efectivos que Participen en Programas de Seguridad Pública (Academia de Policía, Cocinas Móviles)'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '22100002', 'descripcion' => 'Productos Alimenticios para Personas derivado de la Prestación de Servicios Públicos en Unidades de Salud, Educativas, de Readaptación Social y Otras'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '22100003', 'descripcion' => 'Productos Alimenticios para Internos'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '22100004', 'descripcion' => 'Productos Alimenticios para el Personal derivado de Actividades Extraordinarias'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '22100005', 'descripcion' => 'Agua Purificada'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '22200001', 'descripcion' => 'Productos Alimenticios para Animales'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '22300001', 'descripcion' => 'Utensilios para Servicio de Alimentación'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '23100001', 'descripcion' => 'Productos Alimenticios, Agropecuarios y Forestales Adquiridos como Materia Prima'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '23800001', 'descripcion' => 'Mercancías Adquiridas para su Comercialización'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '24100001', 'descripcion' => 'Productos Minerales No Metálicos'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '24200001', 'descripcion' => 'Cemento y Productos de Concreto'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '24300001', 'descripcion' => 'Cal, Yeso y Productos de Yeso'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '24400001', 'descripcion' => 'Madera y Productos de Madera'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '24500001', 'descripcion' => 'Vidrio y Productos de Vidrio'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '24600001', 'descripcion' => 'Material Eléctrico y Electrónico'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '24700001', 'descripcion' => 'Artículos Metálicos para la Construcción'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '24800001', 'descripcion' => 'Plantas de Ornato'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '24900001', 'descripcion' => 'Pinturas'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '25100001', 'descripcion' => 'Sustancias Químicas'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '25200001', 'descripcion' => 'Plaguicidas, Abonos y Fertilizantes'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '25300001', 'descripcion' => 'Medicinas y Productos Farmacéuticos'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '25400001', 'descripcion' => 'Materiales, Accesorios y Suministros Médicos'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '25500001', 'descripcion' => 'Materiales, Accesorios y Suministros de Laboratorio'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '25600001', 'descripcion' => 'Fibras Sintéticas, Hules, Plástico y Derivados'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '26100001', 'descripcion' => 'Combustibles, Lubricantes y Aditivos para Programas de Seguridad Pública'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '26100002', 'descripcion' => 'Combustibles, Lubricantes y Aditivos para Servicios y Operación de Programas Públicos'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '26100003', 'descripcion' => 'Combustibles, Lubricantes y Aditivos para Servicios Administrativos'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '27100001', 'descripcion' => 'Vestuario y Uniformes'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '27200001', 'descripcion' => 'Prendas de Protección'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '27300001', 'descripcion' => 'Artículos Deportivos'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '27400001', 'descripcion' => 'Textiles'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '27500001', 'descripcion' => 'Blancos'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '28100001', 'descripcion' => 'Sustancias y Materiales Explosivos'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '28200001', 'descripcion' => 'Material para Policía y Tránsito'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '28300001', 'descripcion' => 'Prendas de Protección para Seguridad Pública'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '29100001', 'descripcion' => 'Refacciones, Accesorios y Herramientas'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '29100002', 'descripcion' => 'Material para Talleres'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '29200001', 'descripcion' => 'Refacciones y Accesorios Menores de Edificios'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '29400001', 'descripcion' => 'Refacciones y Accesorios de Equipo de Cómputo'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '29600001', 'descripcion' => 'Neumáticos y Cámaras'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '29800001', 'descripcion' => 'Material para Mantenimiento de Maquinaria y Equipo'],
            ['capitulo' => '2000_(Mat._Y_Suministros)', 'partida' => '29900001', 'descripcion' => 'Materiales y Suministros Varios'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '31100001', 'descripcion' => 'Servicio de Energía Eléctrica'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '31300001', 'descripcion' => 'Servicio de Agua Potable'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '31400001', 'descripcion' => 'Servicio Telefónico Convencional'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '31500001', 'descripcion' => 'Servicio de Telefonía Celular'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '31600001', 'descripcion' => 'Servicio de Radiolocalización'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '31600002', 'descripcion' => 'Servicio de Telecomunicaciones'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '31700001', 'descripcion' => 'Servicios de Conducción de Señales Analógicas y Digitales'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '31800001', 'descripcion' => 'Servicio Postal'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '31800002', 'descripcion' => 'Servicio Telegráfico'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '31800003', 'descripcion' => 'Servicio de Mensajería'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '31900001', 'descripcion' => 'Contratación de Otros Servicios'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '32200001', 'descripcion' => 'Arrendamiento de Edificios y Locales'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '32300001', 'descripcion' => 'Arrendamiento de Equipo y Bienes Informáticos'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '32300002', 'descripcion' => 'Arrendamiento de Equipo de Fotocopiado'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '32500001', 'descripcion' => 'Arrendamiento de Equipo de Transporte para Programas de Seguridad Pública'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '32500002', 'descripcion' => 'Arrendamiento de Equipo de Transporte para Servicios y Operación de Programas Públicos'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '32500003', 'descripcion' => 'Arrendamiento de Equipo de Transporte para Servicios Administrativos'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '32500004', 'descripcion' => 'Arrendamiento de Equipo de Transporte para Desastres Naturales'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '32600001', 'descripcion' => 'Arrendamiento de Maquinaria, Otros Equipos y Herramientas'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '32900001', 'descripcion' => 'Otros Arrendamientos'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '32900002', 'descripcion' => 'Arrendamiento de Servicios de Limpieza'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '33100001', 'descripcion' => 'Asesorías Asociadas a Convenios o Acuerdos'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '33100002', 'descripcion' => 'Asesorías por Controversias'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '33200001', 'descripcion' => 'Servicios de Diseño, Arquitectura, Ingeniería y Actividades Relacionadas'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '33300001', 'descripcion' => 'Servicios de Informática'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '33300002', 'descripcion' => 'Servicios Estadísticos y Geográficos'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '33400001', 'descripcion' => 'Capacitación'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '33800001', 'descripcion' => 'Servicios de Vigilancia'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '33900001', 'descripcion' => 'Estudios, Investigaciones y Proyectos'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '34100001', 'descripcion' => 'Servicios Bancarios y Financieros'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '34100002', 'descripcion' => 'Intereses y Comisiones'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '34100003', 'descripcion' => 'Avalúo Técnico de Predios'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '34200001', 'descripcion' => 'Servicios de Cobranza, Investigación Crediticia y Similar'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '34400001', 'descripcion' => 'Fianzas'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '34500001', 'descripcion' => 'Seguros de Bienes Patrimoniales'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '34600001', 'descripcion' => 'Almacenaje, Embalaje y Envase'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '34700001', 'descripcion' => 'Fletes y Maniobras'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '34900001', 'descripcion' => 'Otros Servicios Comerciales'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '35100001', 'descripcion' => 'Conservación y Mantenimiento de Inmuebles (Edificios Públicos)'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '35200001', 'descripcion' => 'Conservación y Mantenimiento de Equipo y Mobiliario de Administración'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '35200002', 'descripcion' => 'Conservación y Mantenimiento de Otros'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '35300001', 'descripcion' => 'Conservación y Mantenimiento de Bienes Informáticos'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '35400001', 'descripcion' => 'Conservación y Mantenimiento de Equipos de Hospitales'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '35500001', 'descripcion' => 'Conservación y Mantenimiento de Vehículos Adscritos a Programas de Seguridad Pública'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '35500002', 'descripcion' => 'Conservación y Mantenimiento de Vehículos Adscritos a Servicios y Operación de Programas Públicos'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '35500003', 'descripcion' => 'Conservación y Mantenimiento de Vehículos Adscritos a Servicios Administrativos'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '35700001', 'descripcion' => 'Conservación y Mantenimiento de Maquinaria y Equipo Pesado'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '35800001', 'descripcion' => 'Servicio de Lavandería, Limpieza, Higiene'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '35900001', 'descripcion' => 'Fumigación'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '36100001', 'descripcion' => 'Publicaciones Oficiales para Difusión e Información'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '36100002', 'descripcion' => 'Publicaciones Oficiales para Licitaciones Públicas y Trámites Administrativos'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '36100003', 'descripcion' => 'Otros Gastos de Publicación, Difusión e Información'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '36100004', 'descripcion' => 'Impresiones'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '36100005', 'descripcion' => 'Difusión de Mensajes Sobre Programas y Actividades Gubernamentales'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '36300001', 'descripcion' => 'Servicios de Creatividad y Preproducción'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '36400001', 'descripcion' => 'Servicios de Revelado de Fotografías'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '36600001', 'descripcion' => 'Difusión de Mensajes Sobre Programas y Actividades Gubernamentales a Través de Internet'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '37100001', 'descripcion' => 'Pasajes Nacionales a Servidores Públicos'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '37100002', 'descripcion' => 'Pasajes Internacionales a Servidores Públicos'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '37200001', 'descripcion' => 'Pasajes Nacionales a Servidores Públicos'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '37200002', 'descripcion' => 'Pasajes Internacionales a Servidores Públicos'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '37500001', 'descripcion' => 'Viáticos Nacionales a Servidores Públicos'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '37600001', 'descripcion' => 'Viáticos Internacionales a Servidores Públicos'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '37800001', 'descripcion' => 'Servicios Integrales de Traslado y Viáticos Aeronáutica'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '37900001', 'descripcion' => 'Traslados Locales'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '37900002', 'descripcion' => 'Hospedajes Extraordinarios'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '38100001', 'descripcion' => 'Atención a Visitantes'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '38200001', 'descripcion' => 'Espectáculos Culturales'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '38200002', 'descripcion' => 'Actividades Cívicas y Festividades'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '38300001', 'descripcion' => 'Congresos y Convenciones'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '38400001', 'descripcion' => 'Exposiciones'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '39100001', 'descripcion' => 'Servicios Funerarios y de Cementerios'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '39200001', 'descripcion' => 'Otros Impuestos, Derechos y Cuotas'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '39400001', 'descripcion' => 'Sentencias y Resoluciones por Autoridad Competente'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '39500001', 'descripcion' => 'Penas, Multas, Accesorios y Actualizaciones'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '39600001', 'descripcion' => 'Otros Gastos por Responsabilidades'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '39800001', 'descripcion' => 'Impuesto Sobre Erogaciones por Remuneraciones al Trabajo Personal'],
            ['capitulo' => '3000_(Serv._Generales)', 'partida' => '39900001', 'descripcion' => 'Fondo Revolvente'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '41200003', 'descripcion' => 'Gastos de Servicios Personales del Poder Legislativo'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '41200004', 'descripcion' => 'Gastos de Materiales y Suministros del Poder Legislativo'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '41200005', 'descripcion' => 'Gastos de Servicios Generales del Poder Legislativo'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '41200006', 'descripcion' => 'Gastos de Transferencias, Asignaciones y Otras Ayudas del Poder Legislativo'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '41200007', 'descripcion' => 'Gastos de Bienes Muebles e Inmuebles del Poder Legislativo'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '41200008', 'descripcion' => 'Gastos de Inversión Pública del Poder Legislativo'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '41200009', 'descripcion' => 'Gastos de Inversiones Financieras del Poder Legislativo'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '41300003', 'descripcion' => 'Gastos de Servicios Personales del Poder Judicial'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '41300004', 'descripcion' => 'Gastos de Materiales y Suministros del Poder Judicial'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '41300005', 'descripcion' => 'Gastos de Servicios Generales del Poder Judicial'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '41300006', 'descripcion' => 'Gastos de Transferencias, Asignaciones y Otras Ayudas del Poder Judicial'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '41300007', 'descripcion' => 'Gastos de Bienes Muebles e Inmuebles del Poder Judicial'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '41300008', 'descripcion' => 'Gastos de Inversión Pública del Poder Judicial'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '41300009', 'descripcion' => 'Gastos de Inversiones Financieras del Poder Judicial'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '41400003', 'descripcion' => 'Gastos de Inversión de los Organismos Autónomos'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '41400004', 'descripcion' => 'Gastos Servicios Personales de los Organismos Autónomos'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '41400005', 'descripcion' => 'Gastos Materiales y Suministros de los Organismos Autónomos'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '41400006', 'descripcion' => 'Gastos Servicios Generales de los Organismos Autónomos'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '41400007', 'descripcion' => 'Gastos Transferencias, Asignaciones y Otras Ayudas de los Organismos Autónomos'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '41400008', 'descripcion' => 'Gastos Bienes Muebles e Inmuebles de los Organismos Autónomos'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '41400009', 'descripcion' => 'Gastos Inversiones Financieras de los Organismos Autónomos'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '41500003', 'descripcion' => 'Subsidios a Entidades Servicios Personales'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '41500004', 'descripcion' => 'Subsidios a Entidades Materiales y Suministros'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '41500005', 'descripcion' => 'Subsidios a Entidades Servicios Generales'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '41500006', 'descripcion' => 'Subsidios a Entidades Transferencias, Asignaciones y Otras Ayudas'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '41500007', 'descripcion' => 'Subsidios a Entidades Bienes Muebles e Inmuebles'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '41500008', 'descripcion' => 'Subsidios a Entidades Inversiones Financieras'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '42500001', 'descripcion' => 'Aportaciones a Fideicomisos Recursos Estatales'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '42500002', 'descripcion' => 'Aportaciones a Fideicomisos Recursos Federales'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '42500003', 'descripcion' => 'Aportaciones para el Fondo de Seguridad Pública Recursos Estatales'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '42500004', 'descripcion' => 'Aportaciones para el Fondo de Seguridad Pública Recursos Federales'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '43300001', 'descripcion' => 'Subsidio a la Inversión'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '43600001', 'descripcion' => 'Subsidio Infonavit'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '43700001', 'descripcion' => 'Subvenciones a la Economía Familiar'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '43800001', 'descripcion' => 'Subsidio a Municipios'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '43900001', 'descripcion' => 'Subsidio Impuesto de la Tenencia'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '43900002', 'descripcion' => 'Subsidios Infraestructura para el Desarrollo'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '43900003', 'descripcion' => 'Subsidios a Entidades Infraestructura'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '43900004', 'descripcion' => 'Obras y Acciones para el Combate a la Pobreza'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '44100001', 'descripcion' => 'Protección a Ancianos y Desvalidos'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '44100002', 'descripcion' => 'Servicios Médicos'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '44100003', 'descripcion' => 'Traslado de Personas'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '44200001', 'descripcion' => 'Becas'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '44300001', 'descripcion' => 'Ayudas Educacionales Recursos Estatales'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '44300002', 'descripcion' => 'Ayudas Educacionales Recursos Federales'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '44400001', 'descripcion' => 'Ayudas Culturales y Científicos'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '44500001', 'descripcion' => 'Ayudas a Instituciones'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '44500002', 'descripcion' => 'Apoyo a Representantes Obreros y Patronales'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '44500003', 'descripcion' => 'Ayudas a Agrupaciones'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '44500004', 'descripcion' => 'Ayudas a Sindicatos'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '44800001', 'descripcion' => 'Ayudas por Desastres Naturales y Otros Siniestros'],
            ['capitulo' => '4000_(Subsidios_y_transf)', 'partida' => '45100001', 'descripcion' => 'Pensiones'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '51100001', 'descripcion' => 'Mobiliario y Equipo de Oficina'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '51200001', 'descripcion' => 'Otros Muebles'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '51300001', 'descripcion' => 'Bienes para Bibliotecas y Museos'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '51500001', 'descripcion' => 'Bienes Informáticos'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '51900001', 'descripcion' => 'Otros Mobiliarios y Equipo de Administración'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '52100001', 'descripcion' => 'Equipo Audiovisual'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '52200001', 'descripcion' => 'Aparatos Deportivos'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '52300001', 'descripcion' => 'Equipo Fotográfico'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '52900001', 'descripcion' => 'Equipos Recreativos'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '52900002', 'descripcion' => 'Instrumentos Musicales'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '52900003', 'descripcion' => 'Muebles Escolares'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '53100001', 'descripcion' => 'Equipo Médico y de Laboratorio'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '53200001', 'descripcion' => 'Instrumental Médico y de Laboratorio'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '54100001', 'descripcion' => 'Vehículos Terrestres para Programas de Seguridad Pública'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '54100002', 'descripcion' => 'Vehículos Terrestres para Servicios y Operación de Programas Públicos'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '54100003', 'descripcion' => 'Vehículos Terrestres para Servicios Administrativos'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '54200001', 'descripcion' => 'Carrocerías y Remolques para Programas de Seguridad Pública'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '54200002', 'descripcion' => 'Carrocerías y Remolques para Programas Servicios y Operación de Programas Públicos'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '54200003', 'descripcion' => 'Carrocerías y Remolques para Servicios Administrativos'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '54300001', 'descripcion' => 'Equipo Aéreo para Programas de Seguridad Pública'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '54300002', 'descripcion' => 'Equipo Aéreo para Programas Servicios y Operación de Programas Públicos'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '54300003', 'descripcion' => 'Equipo Aéreo para Servicios Administrativos'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '54500001', 'descripcion' => 'Marítimos, Lacustres y Fluviales para Programas de Seguridad Pública'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '54500002', 'descripcion' => 'Marítimos, Lacustres y Fluviales para Servicios y Operación de Programas Públicos'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '54500003', 'descripcion' => 'Marítimos, Lacustres y Fluviales para Servicios Administrativos'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '54900001', 'descripcion' => 'Otros Equipos de Transporte'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '55100001', 'descripcion' => 'Equipo para Policía y Tránsito'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '56100001', 'descripcion' => 'Maquinaria y Equipo Agropecuario'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '56200001', 'descripcion' => 'Maquinaria y Equipo Industrial'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '56200002', 'descripcion' => 'Maquinaria y Equipo para Suministro de Agua Potable'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '56300001', 'descripcion' => 'Maquinaria y Equipo de Construcción'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '56400001', 'descripcion' => 'Sistemas de Aire Acondicionado, Calefacción y de Refrigeración Industrial y Comercial'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '56500001', 'descripcion' => 'Equipos y Aparatos de Comunicaciones y Telecomunicaciones'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '56600001', 'descripcion' => 'Maquinaria y Equipo Eléctrico y Electrónico'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '56700001', 'descripcion' => 'Maquinaria y Equipo para Talleres'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '56700002', 'descripcion' => 'Herramientas y Máquinas-Herramienta'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '56700003', 'descripcion' => 'Refacciones Mayores'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '56900001', 'descripcion' => 'Equipos de Medición'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '56900002', 'descripcion' => 'Equipo de Señalamiento'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '56900003', 'descripcion' => 'Equipo de Ingeniería y Dibujo'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '56900004', 'descripcion' => 'Máquinas y Aparatos Científicos'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '56900005', 'descripcion' => 'Maquinaria y Equipo de Imprenta'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '56900006', 'descripcion' => 'Otros Bienes Muebles'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '57800001', 'descripcion' => 'Árboles y Plantas'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '58900003', 'descripcion' => 'Otros Bienes Inmuebles'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '59100001', 'descripcion' => 'Software'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '59200001', 'descripcion' => 'Patentes'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '59300001', 'descripcion' => 'Marcas'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '59400001', 'descripcion' => 'Derechos'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '59500001', 'descripcion' => 'Concesiones'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '59700001', 'descripcion' => 'Licencias Informáticas e Intelectuales'],
            ['capitulo' => '5000_(Bienes)', 'partida' => '59900001', 'descripcion' => 'Otros Activos Intangibles'],
        ];



        foreach ($catalogos as $reparto) {
            ObjetoGasto::create([
                'capitulo' => $reparto['capitulo'],
                'partida' => $reparto['partida'],
                'descripcion' => $reparto['descripcion'],
            ]);
        }
    }
}
